Build Linux Binary (amd64):
  variables:
    NAME: homed-cloud-server
    QT_BUILD: qt-amd64-linux-5.15.4-shared
  script:
  - "docker run --rm -u ${UID}:${UID} -v /opt/qt/${QT_BUILD}:/opt/qt/${QT_BUILD} -v ${PWD}/..:/build -w /build/${NAME} gcc:10.5.0 bash -c \"/opt/qt/${QT_BUILD}/bin/qmake ${NAME}.pro; make -j $(nproc)\""
  artifacts:
    paths:
    - ${NAME}
